#ident "@(#) $Id: lpfwrite.c,v 1.1 2001/03/09 16:12:36 bzfkocht Exp $"
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/*                                                                           */
/*   File....: lpfwrite.c                                                    */
/*   Name....: LP Format File Writer                                         */
/*   Author..: Thorsten Koch                                                 */
/*   Copyright by Author, All rights reserved                                */
/*                                                                           */
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/*
 * Copyright (C) 2001 by Thorsten Koch <koch@zib.de>
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include "mshell.h"
#include "portab.h"
#include "mme.h"
#include "rbt.h"
#include "lpstore.h"

/* A specification for the LP file format can be found in the
 * ILOG CPLEX 7.0 Reference Manual page 527.
 */
void lpf_write(
   const Lps* lp,
   FILE*      fp)
{
   const Var* var;
   const Con* con;
   const Nzo* nzo;
   Bool  first;
   int   cnt;
   
   assert(lp != NULL);
   assert(fp != NULL);

   fprintf(fp, "\\This file was automatically generated by zimple\n");
   fprintf(fp, "\\Problem name: %s\n", lp->name);   
   fprintf(fp, "%s\n", (lp->direct == LP_MIN) ? "Minimize" : "Maximize");
   fprintf(fp, " %s: ", lp->objname == NULL ? "Objective" : lp->objname);
   
   for(var = lp->var_root, cnt = 0; var != NULL; var = var->next)
   {
      if ((var->size > 0) && (fabs(var->cost) > EPS_ZERO))
      {
         fprintf(fp, " %+.16g v%d", var->cost, var->number);

         if (++cnt >= 6)
            printf("\n ");
      }
   }  
   fprintf(fp, "\nSubject to\n");

   for(con = lp->con_root; con != NULL; con = con->next)
   {
      if (con->size == 0)
         continue;
      
      fprintf(fp, " c%d: ", con->number);

      for(nzo = con->first, cnt = 0; nzo != NULL; nzo = nzo->con_next)
      {
         fprintf(fp, " %+.16g v%d", nzo->value, nzo->var->number);

         if (++cnt >= 6)
            printf("\n ");         
      }
      switch(con->type)
      {
         case CON_LE :
            fprintf(fp, " <= ");
            break;
         case CON_GE :
            fprintf(fp, " >= ");
            break;
         case CON_EQ :
            fprintf(fp, " = ");
            break;
         default :
            abort();
      }
      fprintf(fp, "%.16g\n", con->rhs);
   }
   fprintf(fp, "Bounds\n");

   for(var = lp->var_root; var != NULL; var = var->next)
   {
      if ((var->size > 0)
         && (GT(fabs(var->lower), 0.0) || LT(var->upper, INFINITY)))
      {
         if (LE(var->lower, -INFINITY))
            fprintf(fp, " -Inf");
         else
            fprintf(fp, " %.16g", var->lower);

         fprintf(fp, " <= v%d <= ", var->number);
         
         if (GE(var->upper, INFINITY))
            fprintf(fp, "Inf\n");
         else
            fprintf(fp, "%.16g\n", var->upper);
      }
   }
   for(first = TRUE, var = lp->var_root; var != NULL; var = var->next)
   {
      if ((var->size > 0) && (var->type == VAR_INT))
      {
         if (first)
         {
            fprintf(fp, "General\n");
            first = FALSE;
         }
         fprintf(fp, " v%d\n", var->number);
      }
   }
   for(first = TRUE, var = lp->var_root; var != NULL; var = var->next)
   {
      if ((var->size > 0) && (var->type == VAR_BIN))
      {
         if (first)
         {
            fprintf(fp, "Binary\n");
            first = FALSE;
         }
         fprintf(fp, " v%d\n", var->number);
      }
   }
   fprintf(fp, "End\n");
}   



