#ident "@(#) $Id: mpswrite.c,v 1.1 2001/03/09 16:12:36 bzfkocht Exp $"
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/*                                                                           */
/*   File....: mpswrite.c                                                    */
/*   Name....: MPS File Write                                                */
/*   Author..: Thorsten Koch                                                 */
/*   Copyright by Author, All rights reserved                                */
/*                                                                           */
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
/*
 * Copyright (C) 2001 by Thorsten Koch <koch@zib.de>
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <assert.h>
#include "mshell.h"
#include "portab.h"
#include "mme.h"
#include "rbt.h"
#include "lpstore.h"

static void write_data(
   FILE*        fp,
   const int    indicator1,
   const int    indicator2,
   const char*  name1,
   const char*  name2,
   const double value)
{
   assert(name1 != NULL);
   assert(name2 != NULL);
   
   if (fabs(value) > EPS_ZERO)
   {
      fprintf(fp, " %c%c %-8.8s  %-8.8s  %12g\n",
         toupper(indicator1), toupper(indicator2), name1, name2, value);
   }
   else
   {
      fprintf(fp, " %c%c %-8.8s  %-8.8s\n",
         toupper(indicator1), toupper(indicator2), name1, name2);
   }
}   

static void write_vars(
   const Lps* lp,
   FILE*      fp,
   VarType    vartype)
{
   const Var*  var;
   const Nzo*  nzo;
   char  vtmp  [13];
   char  ctmp  [13];
   
   assert(lp != NULL);
   assert(fp != NULL);

   for(var = lp->var_root; var != NULL; var = var->next)
   {
      if (var->type != vartype)
         continue;

      if (fabs(var->cost) > EPS_ZERO)
      {
         sprintf(vtmp, "v%d", var->number);
         write_data(fp, ' ', ' ', vtmp, "OBJECTIV",
            (lp->direct == LP_MIN) ? var->cost : -var->cost);
      }
      for(nzo = var->first; nzo != NULL; nzo = nzo->var_next)
      {
         assert(nzo->var == var);
         assert(fabs(nzo->value) > EPS_ZERO);
         
         sprintf(vtmp, "v%d", var->number);
         sprintf(ctmp, "c%d", nzo->con->number);

         write_data(fp, ' ', ' ', vtmp, ctmp, nzo->value);
      }
   }   
}

void mps_write(
   const Lps* lp,
   FILE*      fp)
{
   const Var*  var;
   const Con*  con;
   char  vtmp  [13];
   char  ctmp  [13];
   
   assert(lp != NULL);
   assert(fp != NULL);

   fprintf(fp, "* This file was automatically generated by zimple\n");
   fprintf(fp, "NAME        %8.8s\n", lp->name);
   fprintf(fp, "ROWS\n");
   
   write_data(fp, 'N', ' ', "OBJECTIV", "", 0.0);

   for(con = lp->con_root; con != NULL; con = con->next)
   {
      sprintf(ctmp, "c%d", con->number);
      write_data(fp, lps_getsense(con), ' ', ctmp, "", 0.0);
   }
   fprintf(fp, "COLUMNS\n");

   /* First integer/binary variables
    */
   if (lp->type != LP_LP)
   {
      fprintf(fp, "    MARK0000  'MARKER'                 'INTORG'\n");

      write_vars(lp, fp, VAR_INT);
      write_vars(lp, fp, VAR_BIN);

      fprintf(fp, "    MARK0001  'MARKER'                 'INTEND'\n");
   }
   write_vars(lp, fp, VAR_CON);

   fprintf(fp, "RHS\n");
   
   for(con = lp->con_root; con != NULL; con = con->next)
   {
      if (fabs(con->rhs) > EPS_ZERO)
      {
         sprintf(ctmp, "c%d", con->number);
         write_data(fp, ' ', ' ', "RHS", ctmp, con->rhs);
      }
   }
   fprintf(fp, "BOUNDS\n");

   for(var = lp->var_root; var != NULL; var = var->next)
   {
      /*   0, oo  -> nix
       *   l, oo  -> LO
       *   0, u   -> UP
       *   l = u  -> FX
       */
      sprintf(vtmp, "v%d", var->number);

      if (fabs(var->lower) > EPS_ZERO)
         write_data(fp, 'L', 'O', "BOUND", vtmp, var->lower);

      if (fabs(var->upper) < INFINITY)
         write_data(fp, 'U', 'P', "BOUND", vtmp, var->upper);
   }
   fprintf(fp, "ENDATA\n");
}   


