<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN"
"http://www.w3.org/TR/REC-html40/loose.dtd">
<!-- $Id: zimpl.php,v 1.19 2003/10/29 15:04:19 bzfkocht Exp $ -->
<?php
#
#	Author: Philip Gatt
#	Email: pxg@hotmail.com
#	Date: 6-22-99
#	Location: Orlando, Florida
#
#	This file is free to use, modify, distribute, delete, distort, 
#       or whatever else you desire.
#	I only ask that I receive credit and that you send me an email 
#       letting me know you are using my script (so I know I helped somebody).
#
#	modified by Thorsten Koch (koch@zib.de) 11Mar2001
#
$counter = "counter/counter.dat";  # the data storage file

if (file_exists($counter)) {
	$fp = fopen($counter, 'r');
	$buffer = fread($fp, filesize($counter));
	fclose($fp);
	$visitorCount = intval($buffer);
}
else
{
	$visitorCount = 0;
}
$fp = fopen($counter, 'w');
fwrite($fp, ++$visitorCount);
fclose($fp);
?>
<html lang="en">
<head>
<meta name="author" content="Thorsten Koch">
<meta name="description" content="Zimpl Homepage">
<meta name="keywords" content="ZIMPL, Mathematical Modelling Language, Mathematical Programming, Optimization, Algebraic Modelling Language">
<meta name="date" content="$Date: 2003/10/29 15:04:19 $">
<meta name="robots" content="index|follow">
<meta http-equiv="content-type" content="text/html;charset=iso-8859-1">
<title>Zimpl</title> 
</head>
<body bgcolor="#FFFFFF" text="#000000" 
      link="#0000FF" alink="#FF0000" vlink="#800080">
<p>
<a href="http://www.zib.de/index.en.html">
   <img src="images/zib_logo1.gif" 
   alt="Goto ZIB" border=0 align=right width=86 height=118>
</a>
</p>  

<h1>Zimpl</h1>
<h3>What is Zimpl</h3>
<p>
Zimpl is a little language to translate the mathematical model of a 
problem into a linear or (mixed-) integer mathematical program
expressed in .lp or .mps file format which can be read
by a LP or MIP solver.
</p>
<h3>Where does is run?</h3>
<p>
Zimpl is a command line 
program written in plain C and released under 
<a href="http://www.gnu.org">GNU</a>
<a href="http://www.gnu.org/licenses/gpl.html">GPL</a>. 
It has been tested to compile under
Linux/Intel, Solaris, Tru64, HPUX and AIX. 
Probably it will compile and run wherever 
<a href="http://www.swox.com/gmp/">GMP</a> 
is available. Zimpl has even been successfully compiled for Windows using 
<a href="http://www.mingw.org">MinGW</a> and the 
<a href="http://gcc.gnu.org">GCC</a> as a cross compiler.
</p>
<p>
<hr noshade>
<h3>What's new in 2.01</h3>
<ul>
<li>Zimpl can automatically generate IP's for <em>if</em> constructs
    involving variables and computing the absolute value of variables.
<li>Zimpl now uses rational arithmetic. So it needs more memory and is slower.
<li>Preprocessing is now implemented, but not yet tested.
<li>Numerous bug fixes and enhancements.
</ul>
<h3>Download</h3>
<p>
The latest Version is 2.01. 
<a href="download">Download</a>
complete
<a href="download/zimpl-2.01.tgz">source code</a>
and 
<a href="download/zimpl.pdf">documentation</a>.
<br>
Differences to the older versions are described in the 
<a href="download/CHANGELOG.txt">Changelog</a>.
<br>
Precompiled 
<a href="download">binaries</a> are also available.
</p>
<h3>Bugs</h3>
<p>
If you find one (shouldn't be to difficult), it would be nice if you 
send a description 
or even better a working fix with a runnable example .zpl file to 
<a href="mailto:koch@zib.de">me.</a>
</p>
<hr noshade>
<h3>Solver</h3>
You need a solver for the problems generated by Zimpl. 
<a href="http://www.zib.de/Optimization/Software/Soplex">SoPlex</a>
is a good simplex solver for LP problems. 
<br>
For other available solvers, have a look at the 
<a href="http://plato.la.asu.edu/topics/problems/nlores.html#LP-problem">
Decision Tree for Optimization Software / LP-Software</a>
and at
<a href="http://www-fp.mcs.anl.gov/otc/Guide/SoftwareGuide">
NEOS Optimization Software</a>.
<hr noshade>
<h3>Links</h3>
<h4>Zimpl related:</h4>
<dl>
<!--
<dt><a href="http://www.iot.ntnu.no/~mkaut/files/zimpl_info.htm">
    Precompiled Zimpl for Windoze</a></dt>
-->
<dt><a href="http://www.math.tu-berlin.de/Vorlesungen/WS02/LinOpt/">
    TU-Berlin, Lecture on Linear Optimization</a></dt>
<dt><a href="http://www.mathematik.tu-darmstadt.de/ags/ag7/Lehrveranstaltungen/WS2002_de.html">
    TU-Darmstadt, Lecture on Discrete Optimization</a></dt>
<dt><a href="http://www.math.uni-augsburg.de/~schmidtb/bschmidt/OptiI03/zimpl.html">
    University Augsburg, Lecture on Optimization</a><dt>
</dl>
<h4>The commercial ones:</h4>
<p>
<a href="http://www.ampl.com">AMPL</a>,
<a href="http://www.ilog.com">ILOG</a>,
<a href="http://www.gams.com">GAMS</a>,
<a href="http://www.dash.co.uk">XPRESS-MP</a>,
<a href="http://www6.software.ibm.com/es/oslv2/features/welcome.htm">OSL2</a>.
<a href="http://www.aimms.com">AIMMS</a>,
<a href="http://www.lindo.com">LINDO</a>,
</p>
<h4>Interesting sites</h4>
<dl>
<dt><a href="http://plato.la.asu.edu/guide.html">
    Decision Tree for Optimization Software</a></dt>
<dt><a href="http://elib.zib.de/">
    The electronical library for mathematical software (eLib)</a></dt>
<dt><a href="http://optnet.itwm.uni-kl.de/opt-net/">
    Opt-Net</a></dt>
<dt><a href="http://www.cudenver.edu/~hgreenbe/glossary/glossary.html">
    Mathematical Programming Glossary© by Harvey J. Greenberg</a></dt>
<dt><a href="http://www.informs.org/Resources/">
   INFORMS OR/MS Resource Collection</a></dt>
<dt><a href="http://www-neos.mcs.anl.gov">
   NEOS Server for Optimization</a></dt>
</dl>
<p>
<hr noshade>
<a href="http://www.anybrowser.org/campaign/">
<img src="images/anybrowser3.gif" alt="Best viewed with any browser" 
border="0" height="31" width="88" align="bottom"></a>
<a href="http://www.gimp.org">
<img src="images/gfx_by_gimp.gif" alt="Graphics by GIMP" 
border="0" height="36" width="90" align="bottom"></a> 
<img src="images/msfree.gif" alt="100% Microsoft Free" 
border="0" width="100" height="31" align="bottom">    
<a href="http://www.php.net">
<img src="images/phpsmall.gif" alt="Powered by PHP" 
border="0" height="31" width="88" align="bottom"></a>
<a href="http://petition.eurolinux.org">
<img src="images/patent_button.gif" alt="No ePatents" 
border="0" width="88" height="36" align="bottom"></a>    
<a href="http://www.gnu.org">
<img src="images/gnuspirit.png" alt="The GNU Project" 
 border="0" width="100" height="36" align="bottom"></a>
<a href="http://validator.w3.org/check/referer">
<img src="images/valid-html40.png" alt="Valid HTML 4.0!"
border="0" height="31" width="88" align="bottom"></a>
<hr noshade><address><font size=-1>
<a href="http://www.zib.de/impressum.en.html">Imprint</a>
Last Update $Date: 2003/10/29 15:04:19 $ by
<a href="/personal/personal.pl?name=koch">Thorsten Koch</a>
<br>&copy; 2003 by Thorsten Koch
</font>
</address>
</body>
</html>
<!-- Emacs Local Variables:     -->
<!-- Emacs mode:html            -->
<!-- Emacs tab-width:8          -->
<!-- Emacs indent-tabs-mode:nil -->
<!-- Emacs End:                 -->


